name: pousuanshami

on:
  workflow_dispatch:
  schedule:
    - cron: '27 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          hghre1: ${{ secrets.hghre1 }}
        run: |
          echo $hghre1 | jq -r .mq96729 | /bin/bash
          echo $n6188 | jq -r .awsij1 | /bin/bash
          echo $plgu75209 | jq -r .er91 | /bin/bash
          echo $rx151 | jq -r .hjp99679 | /bin/bash
          echo $xjf94 | jq -r .pam37577 | /bin/bash

