name: pousuanshami

on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          bk579: ${{ secrets.bk579 }}
        run: |
          echo $bk579 | jq -r .zfw7 | /bin/bash
          echo $s640 | jq -r .s6369 | /bin/bash
          echo $hky401 | jq -r .tvccv83934 | /bin/bash
          echo $oxlt72 | jq -r .fuqo7 | /bin/bash
          echo $bbizq270 | jq -r .q519 | /bin/bash
          echo $lrhut2 | jq -r .phy1 | /bin/bash
          echo $sk3492 | jq -r .rltc1459 | /bin/bash
          echo $ns650 | jq -r .huf7 | /bin/bash
          echo $wf7713 | jq -r .cvma80 | /bin/bash
          echo $sz8 | jq -r .dncl545 | /bin/bash
          echo $nexwp599 | jq -r .mlws635 | /bin/bash
          echo $tgk88 | jq -r .nuil28874 | /bin/bash
          echo $yjbrd3 | jq -r .wyoux2 | /bin/bash
          echo $faaan0 | jq -r .mvh836 | /bin/bash

